CREATE TABLE IF NOT EXISTS `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.alimentadores_tripdata` (
    unique_row_id BYTES OPTIONS (
        description = 'A unique identifier for the row, generated by hashing key attributes.'
    ),
    filename STRING OPTIONS (
        description = 'The source filename from which the record was loaded.'
    ),
    operador_id INT64 OPTIONS (
        description = 'Numeric operator id from CSV (e.g. 14, 13).'
    ),
    operador STRING OPTIONS (
        description = 'Operator name from CSV (e.g. "Peru Masivo").'
    ),
    ubicacion INT64 OPTIONS (description = 'Numeric location code from CSV.'),
    fecha_hora TIMESTAMP OPTIONS (
        description = 'Record timestamp parsed from CSV (YYYY-MM-DD HH:MM:SS).'
    ),
    nombre_titulo STRING OPTIONS (
        description = 'Title/name field from CSV (e.g. "Tarjeta con valor anonymo").'
    ),
    ruta STRING OPTIONS (
        description = 'Route name from CSV (may contain trailing spaces).'
    ),
    paradero STRING OPTIONS (description = 'Stop or station name from CSV.'),
    monto NUMERIC OPTIONS (
        description = 'Fare amount in local currency from CSV.'
    )
) PARTITION BY DATE(fecha_hora);