CREATE TABLE IF NOT EXISTS `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.troncales_tripdata` (
    unique_row_id BYTES OPTIONS (
        description = 'A unique identifier for the record, generated by hashing key attributes.'
    ),
    filename STRING OPTIONS (
        description = 'The source filename from which the record was loaded.'
    ),
    block_id INT64 OPTIONS (description = 'Block identifier from schedule.'),
    fecha_hora_incidencia TIMESTAMP OPTIONS (
        description = 'Incident timestamp parsed from source CSV.'
    ),
    route_name STRING OPTIONS (
        description = 'Route name, e.g. "RB - Regular B"'
    ),
    tp_sname STRING OPTIONS (
        description = 'Trip pattern short name or stop short name.'
    ),
    direction_description STRING OPTIONS (description = 'Direction, e.g. "Sur" or "Norte"'),
    pod STRING OPTIONS (
        description = 'Planned time of departure as string (e.g. 6:36:00).'
    ),
    hora_sched STRING OPTIONS (
        description = 'Scheduled hour or time as present in source CSV.'
    ),
    deviation INT64 OPTIONS (
        description = 'Deviation in minutes from schedule.'
    ),
    vehicle_id INT64 OPTIONS (description = 'Vehicle identifier.'),
    mes STRING OPTIONS (description = 'Month name from source CSV.')
) PARTITION BY DATE(fecha_hora_incidencia);